url: mtlallgirlhacknight.ca
twitter: mtlgirlhackers
email: mtlallgirlhacknight@gmail.com

is_there_a_plan: yes

when: March 25, 2013
where: Coming soon!
where_url: 

sponsor_url: 
sponsor_image: 
sponsor_image_size: 60

eventbrite_id: 
