url: mtlallgirlhacknight.ca
twitter: mtlgirlhackers
email: mtlallgirlhacknight@gmail.com

is_there_a_plan: yes

when: "6:45, April 1st, 2013"
where: "Password Box"
where_url: "https://www.google.com/maps/place/4200+Boulevard+Saint-Laurent+%23610/@45.5181162,-73.582401,17z/data=!4m2!3m1!1s0x4cc91bcd597c6333:0xfe46d5188228b74c"

sponsor_url: "https://www.passwordbox.com/"
sponsor_image: "https://assets-production.psswrdbx.com/images/logos/pb-logo-xx-large.png?1394037573"
sponsor_image_size: 60

eventbrite_id: 10870687519
