url: mtlallgirlhacknight.ca
twitter: mtlgirlhackers
email: mtlallgirlhacknight@gmail.com

is_there_a_plan: no

when: February-ish
where:
where_url:

sponsor_url:
sponsor_image:
sponsor_image_size: 60

eventbrite_id:
