url: mtlallgirlhacknight.ca
twitter: mtlgirlhackers
email: mtlallgirlhacknight@gmail.com

is_there_a_plan: yes

when: "18:30, 19 February 2014"
where: Google Montreal
where_url: "http://goo.gl/L6dQFg"

sponsor_url: "http://www.google.com"
sponsor_image: "http://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Logo_Google_2013_Official.svg/251px-Logo_Google_2013_Official.svg.png"
sponsor_image_size: 60

eventbrite_id: 10533751735
